#!/usr/bin/env bash
# Regenerate checked-in mock heal demo artifacts (no API keys required).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DEMO_DIR="examples/demo/fibonacci-heal"
TRANSCRIPT="docs/demo/heal-fibonacci.md"
CAST="docs/demo/heal-fibonacci.cast"

mkdir -p "$DEMO_DIR" docs/demo

# Prefer poetry if available; fall back to python -m.
if command -v poetry >/dev/null 2>&1 && [[ -f pyproject.toml ]]; then
  RUN=(poetry run ascl)
elif [[ -x .venv/bin/python ]]; then
  RUN=(.venv/bin/python -m ascl)
else
  RUN=(python3 -m ascl)
fi

TMP_OUT="$(mktemp)"
cleanup() { rm -f "$TMP_OUT"; }
trap cleanup EXIT

set +e
ASCL_PROVIDER=mock "${RUN[@]}" heal \
  --provider mock \
  --no-lint \
  --prompt "$(cat examples/fibonacci/PROMPT.txt)" \
  --tests examples/fibonacci/test_fib.py \
  --max-iterations 4 \
  --artifact-dir "$DEMO_DIR" \
  >"$TMP_OUT" 2>&1
STATUS=$?
set -e

# Keep JSON + per-iteration folders; drop scratch workspace.
rm -rf "$DEMO_DIR/workspace"

# Write regenerator helper next to artifacts.
cat >"$DEMO_DIR/command.sh" <<'EOF'
#!/usr/bin/env bash
# Exact command used to regenerate this demo (invoked via scripts/regenerate_demo.sh).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
cd "$ROOT"
exec bash scripts/regenerate_demo.sh
EOF
chmod +x "$DEMO_DIR/command.sh"

# Markdown transcript always (GitHub-visible).
{
  echo "# Terminal transcript: mock fibonacci heal"
  echo
  echo "Regenerated by \`scripts/regenerate_demo.sh\` (provider=mock)."
  echo
  echo '```text'
  cat "$TMP_OUT"
  echo '```'
  echo
  echo "Exit status: \`$STATUS\`"
} >"$TRANSCRIPT"

# Optional asciinema cast when the CLI is installed.
if command -v asciinema >/dev/null 2>&1; then
  # Record a short playback-friendly cast by wrapping the same command.
  asciinema rec "$CAST" --overwrite --quiet --command \
    "ASCL_PROVIDER=mock ${RUN[*]} heal --provider mock --no-lint --prompt \"\$(cat examples/fibonacci/PROMPT.txt)\" --tests examples/fibonacci/test_fib.py --max-iterations 4 --artifact-dir /tmp/ascl-demo-cast" \
    || true
fi

# Optional GIF for GitHub README when agg is installed.
GIF="docs/demo/heal-fibonacci.gif"
if command -v agg >/dev/null 2>&1 && [[ -f "$CAST" ]]; then
  agg --speed 1.5 --font-size 14 --theme monokai "$CAST" "$GIF" || true
  echo "GIF written to $GIF"
fi

echo "Demo artifacts written to $DEMO_DIR"
echo "Transcript written to $TRANSCRIPT"
exit "$STATUS"
